CREATE TABLE public.seda_schools
(
    id character varying(12) COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default",
    city text COLLATE pg_catalog."default",
    state_name text COLLATE pg_catalog."default",
    state character(2) COLLATE pg_catalog."default" NOT NULL,
    all_frl numeric,
    all_avg numeric,
    all_coh numeric,
    all_grd numeric,
    all_sz numeric,
    lat numeric,
    lon numeric,
    w_pct numeric,
    b_pct numeric,
    a_pct numeric,
    i_pct numeric,
    h_pct numeric,
    CONSTRAINT seda_schools_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.seda_schools
    OWNER to postgres;

CREATE TABLE public.seda_counties
(
    id character varying(5) COLLATE pg_catalog."default" NOT NULL,
    lat numeric,
    lon numeric,
    name text COLLATE pg_catalog."default",
    all_ses numeric,
    w_ses numeric,
    b_ses numeric,
    h_ses numeric,
    wb_ses numeric,
    wh_ses numeric,
    wb_seg numeric,
    wh_seg numeric,
    np_seg numeric,
    wb_min numeric,
    wh_min numeric,
    state character(2) COLLATE pg_catalog."default" NOT NULL,
    all_sz numeric,
    all_avg numeric,
    all_grd numeric,
    all_coh numeric,
    a_sz numeric,
    a_avg numeric,
    a_grd numeric,
    a_coh numeric,
    b_sz numeric,
    b_avg numeric,
    b_grd numeric,
    b_coh numeric,
    p_sz numeric,
    p_avg numeric,
    p_grd numeric,
    p_coh numeric,
    f_sz numeric,
    f_avg numeric,
    f_grd numeric,
    f_coh numeric,
    h_sz numeric,
    h_avg numeric,
    h_grd numeric,
    h_coh numeric,
    m_sz numeric,
    m_avg numeric,
    m_grd numeric,
    m_coh numeric,
    mf_sz numeric,
    mf_avg numeric,
    mf_grd numeric,
    mf_coh numeric,
    np_sz numeric,
    np_avg numeric,
    np_grd numeric,
    np_coh numeric,
    wa_sz numeric,
    pn_sz numeric,
    pn_avg numeric,
    pn_grd numeric,
    pn_coh numeric,
    wa_avg numeric,
    wa_grd numeric,
    wa_coh numeric,
    wb_sz numeric,
    wb_avg numeric,
    wb_grd numeric,
    wb_coh numeric,
    wh_sz numeric,
    wh_avg numeric,
    wh_grd numeric,
    wh_coh numeric,
    w_sz numeric,
    w_avg numeric,
    w_grd numeric,
    w_coh numeric,
    state_name text COLLATE pg_catalog."default",
    CONSTRAINT seda_counties_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.seda_counties
    OWNER to postgres;

CREATE TABLE public.seda_districts
(
    id character varying(7) COLLATE pg_catalog."default" NOT NULL,
    lat numeric,
    lon numeric,
    name text COLLATE pg_catalog."default",
    all_ses numeric,
    w_ses numeric,
    b_ses numeric,
    h_ses numeric,
    wb_ses numeric,
    wh_ses numeric,
    wb_seg numeric,
    wh_seg numeric,
    np_seg numeric,
    wb_min numeric,
    wh_min numeric,
    state character(2) COLLATE pg_catalog."default" NOT NULL,
    all_sz numeric,
    all_avg numeric,
    all_grd numeric,
    all_coh numeric,
    a_sz numeric,
    a_avg numeric,
    a_grd numeric,
    a_coh numeric,
    b_sz numeric,
    b_avg numeric,
    b_grd numeric,
    b_coh numeric,
    p_sz numeric,
    p_avg numeric,
    p_grd numeric,
    p_coh numeric,
    f_sz numeric,
    f_avg numeric,
    f_grd numeric,
    f_coh numeric,
    h_sz numeric,
    h_avg numeric,
    h_grd numeric,
    h_coh numeric,
    m_sz numeric,
    m_avg numeric,
    m_grd numeric,
    m_coh numeric,
    mf_sz numeric,
    mf_avg numeric,
    mf_grd numeric,
    mf_coh numeric,
    np_sz numeric,
    np_avg numeric,
    np_grd numeric,
    np_coh numeric,
    wa_sz numeric,
    pn_sz numeric,
    pn_avg numeric,
    pn_grd numeric,
    pn_coh numeric,
    wa_avg numeric,
    wa_grd numeric,
    wa_coh numeric,
    wb_sz numeric,
    wb_avg numeric,
    wb_grd numeric,
    wb_coh numeric,
    wh_sz numeric,
    wh_avg numeric,
    wh_grd numeric,
    wh_coh numeric,
    w_sz numeric,
    w_avg numeric,
    w_grd numeric,
    w_coh numeric,
    state_name text COLLATE pg_catalog."default",
    CONSTRAINT seda_districts_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.seda_districts
    OWNER to postgres;